#! /bin/bash
SCRIPTPATH=$(dirname $0)
echo $SCRIPTPATH

for i in *.out; do

	if [ -f $i ]; then

		echo $i;

		#Clean up Ptolemy output - output only angles and cross-sections
		python $SCRIPTPATH/ptclean.py $i
		
		else echo 'No .out files found';

	fi;

done;
